import { VideoPreset } from "./types";

/**
 * DZVN Beats Video Presets — Complete Library
 *
 * 14 Distinct Visual Identities:
 *   7 × Landscape (16:9) — YouTube, SoundCloud, Spotify Canvas wide
 *   7 × Portrait  (9:16) — YouTube Shorts, TikTok, Instagram Reels
 *
 * Effect coverage: every registered effect appears in at least one preset.
 * Colors are per-preset, not globally defaulted — auto-color-match will
 * harmonize these on load from the cover art palette extraction.
 */
export const VIDEO_PRESETS: VideoPreset[] = [

  // =========================================================================
  // BLANK CANVASES (transparent starting points)
  // =========================================================================
  {
    id: "blank-transparent",
    name: "Blank Canvas",
    description: "Pristine transparent canvas. Build your own stack from scratch.",
    aspectRatio: "16:9",
    effects: [
      { id: "bg-blurred-cover",     enabled: false },
      { id: "bg-mesh-gradient",     enabled: false },
      { id: "bg-radial-spotlight",  enabled: false },
      { id: "bg-cyber-grid",        enabled: false },
      { id: "hero-vinyl-deck",      enabled: false },
      { id: "hero-solo-vinyl",      enabled: false },
      { id: "hero-cover-art-shadow",enabled: false },
      { id: "hero-cassette-deck",   enabled: false },
      { id: "hero-thumping-art",    enabled: false },
      { id: "part-bokeh-back",      enabled: false },
      { id: "vis-spectrum-bars",    enabled: false },
      { id: "vis-simple-bars",      enabled: false },
      { id: "vis-fluid-wave",       enabled: false },
      { id: "vis-circular-donut",   enabled: false },
      { id: "vis-adaptive-triband", enabled: false },
      { id: "vis-led-vu-meter",     enabled: false },
      { id: "vis-neon-oscilloscope",enabled: false },
      { id: "part-sparks-fore",     enabled: false },
      { id: "part-fire-embers",     enabled: false },
      { id: "hero-simple-max-cover",enabled: false },
      { id: "vis-side-bars",        enabled: false },
      { id: "vis-shockwave-rings",  enabled: false },
      { id: "post-exposure-pulse",  enabled: false },
      { id: "post-vignette-grain",  enabled: false },
      { id: "post-rgb-glitch",      enabled: false },
      { id: "debug-grid-guides",    enabled: false },
    ],
  },
  {
    id: "blank-transparent-shorts",
    name: "Blank Shorts",
    description: "Pristine transparent 9:16 canvas for vertical video creation.",
    aspectRatio: "9:16",
    effects: [
      { id: "bg-blurred-cover",     enabled: false },
      { id: "bg-mesh-gradient",     enabled: false },
      { id: "bg-radial-spotlight",  enabled: false },
      { id: "bg-cyber-grid",        enabled: false },
      { id: "hero-vinyl-deck",      enabled: false },
      { id: "hero-solo-vinyl",      enabled: false },
      { id: "hero-cover-art-shadow",enabled: false },
      { id: "hero-simple-max-cover",enabled: false },
      { id: "hero-cassette-deck",   enabled: false },
      { id: "hero-thumping-art",    enabled: false },
      { id: "part-bokeh-back",      enabled: false },
      { id: "vis-spectrum-bars",    enabled: false },
      { id: "vis-simple-bars",      enabled: false },
      { id: "vis-side-bars",        enabled: false },
      { id: "vis-shockwave-rings",  enabled: false },
      { id: "vis-fluid-wave",       enabled: false },
      { id: "vis-circular-donut",   enabled: false },
      { id: "vis-adaptive-triband", enabled: false },
      { id: "vis-led-vu-meter",     enabled: false },
      { id: "vis-neon-oscilloscope",enabled: false },
      { id: "part-sparks-fore",     enabled: false },
      { id: "part-fire-embers",     enabled: false },
      { id: "hud-track-info",       enabled: false },
      { id: "post-exposure-pulse",  enabled: false },
      { id: "post-vignette-grain",  enabled: false },
      { id: "post-rgb-glitch",      enabled: false },
      { id: "debug-grid-guides",    enabled: false },
    ],
  },

  // =========================================================================
  // LANDSCAPE PRESETS (16:9)
  // =========================================================================

  // --- 1. VINYL LOUNGE ---
  // Aesthetic: warm analog audiophile. Blurred cover art, spinning vinyl with
  // tonearm drop animation, circular donut ring + bokeh particles.
  // HUD: Classic two-column layout (title left, meta badges right).
  {
    id: "vinyl-lounge",
    name: "Vinyl Record Lounge",
    description: "Warm analog audiophile lounge — spinning vinyl tonearm drop, circular donut spectrograph, golden bokeh, and classic two-column HUD.",
    aspectRatio: "16:9",
    effects: [
      { id: "bg-blurred-cover",
        enabled: true,
        options: { blurAmount: 38, darken: 0.58, zoom: 1.2, pulseWithBass: true } },
      { id: "part-bokeh-back",
        enabled: true,
        options: { layer: "back", particleCount: 50, baseSpeed: 0.4, emberColor: "#fbbf24", reactToKick: false } },
      { id: "vis-circular-donut",
        enabled: true,
        options: { barCount: 80, maxBarLength: 80, barWidth: 4, rotationSpeed: 0.12, color: "#f59e0b", glow: true, kickReaction: true } },
      { id: "hero-vinyl-deck",
        enabled: true,
        options: { introDuration: 2.5, showTonearm: true, rpmSpeed: 33.33 } },
      { id: "part-sparks-fore",
        enabled: true,
        options: { layer: "front", particleCount: 55, baseSpeed: 0.9, emberColor: "#fde68a", reactToKick: true } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "classic", showBpmKey: true, showTimer: true, showAudioSpecs: false, accentColor: "#f59e0b", titleFont: "outfit", badgeStyle: "glass" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.62, grainIntensity: 0.035 } },
    ],
  },

  // --- 2. STUDIO CONSOLE ---
  // Aesthetic: high-contrast recording studio control room.
  // Radial spotlight on vinyl, LED VU console meters, classic corner stamp.
  {
    id: "studio-console",
    name: "Studio Control Room",
    description: "High-contrast studio spotlight on the vinyl platter — LED VU console meters, retro CRT oscilloscope, and editorial corner stamp.",
    aspectRatio: "16:9",
    effects: [
      { id: "bg-radial-spotlight",
        enabled: true,
        options: { spotlightColor: "#fbbf24", intensity: 0.9, radiusMultiplier: 1.0, reactToKick: true } },
      { id: "hero-vinyl-deck",
        enabled: true,
        options: { introDuration: 2.0, showTonearm: true, rpmSpeed: 45 } },
      { id: "vis-led-vu-meter",
        enabled: true,
        options: { segmentCount: 24, showDbLabels: true, mode: "triband", glow: true } },
      { id: "vis-neon-oscilloscope",
        enabled: true,
        options: { color: "#10b981", beamThickness: 2.2, glowIntensity: 1.0, amplitude: 1.1, showCenterLine: true } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "corner-stamp", showBpmKey: true, showTimer: true, showAudioSpecs: true, accentColor: "#fbbf24", titleFont: "mono", badgeStyle: "solid" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.72, grainIntensity: 0.045 } },
    ],
  },

  // --- 3. DARK TRAP REACTOR ---
  // Aesthetic: hard-hitting 808 energy. Blurred cover, thumping artwork bounce,
  // fire embers, LED VU console, RGB glitch on kicks, Lower-Third HUD.
  {
    id: "dark-trap-reactor",
    name: "Dark Trap 808 Reactor",
    description: "Sub-bass speaker bounce, rising fire embers, LED VU console, RGB glitch impact on every kick, and bold broadcast Lower-Third.",
    aspectRatio: "16:9",
    effects: [
      { id: "bg-blurred-cover",
        enabled: true,
        options: { blurAmount: 52, darken: 0.70, zoom: 1.25, pulseWithBass: true } },
      { id: "hero-thumping-art",
        enabled: true,
        options: { thumpStrength: 0.16, glowIntensity: 1.2, glowColor: "#dc2626", cornerRadius: 20, sizeScale: 1.0 } },
      { id: "vis-led-vu-meter",
        enabled: true,
        options: { segmentCount: 22, showDbLabels: true, mode: "triband", glow: true } },
      { id: "vis-simple-bars",
        enabled: true,
        options: { barCount: 36, maxHeight: 55, barWidth: 5, barGap: 4, roundedCaps: false, mirror: false, gradientTips: false, glow: false, color: "#ef4444" } },
      { id: "part-fire-embers",
        enabled: true,
        options: { layer: "front", particleCount: 70, baseSpeed: 1.5, reactToKick: true } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "lower-third", showBpmKey: true, showTimer: true, showAudioSpecs: true, accentColor: "#ef4444", titleFont: "outfit", badgeStyle: "solid" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.75, grainIntensity: 0.05 } },
      { id: "post-rgb-glitch",
        enabled: true,
        options: { glitchIntensity: 1.2, chromaticShift: 12, onlyOnKick: true } },
    ],
  },

  // --- 4. LOFI TAPE CHILL ---
  // Aesthetic: warm vintage tape machine. Blurred cover, cassette deck, floating
  // dust bokeh, phosphor CRT oscilloscope, Spotify-style Now Playing pill.
  {
    id: "lofi-tape-chill",
    name: "Lofi Analog Tape Chill",
    description: "Vintage cassette tape mechanism, warm dust bokeh, phosphor CRT oscilloscope, and Spotify Now-Playing glass pill.",
    aspectRatio: "16:9",
    effects: [
      { id: "bg-blurred-cover",
        enabled: true,
        options: { blurAmount: 44, darken: 0.52, zoom: 1.15, pulseWithBass: false } },
      { id: "part-bokeh-back",
        enabled: true,
        options: { layer: "back", particleCount: 60, baseSpeed: 0.3, emberColor: "#fde68a", reactToKick: false } },
      { id: "hero-cassette-deck",
        enabled: true,
        options: { shellColor: "#292524", accentColor: "#d97706", tapeSpeed: 0.8 } },
      { id: "vis-neon-oscilloscope",
        enabled: true,
        options: { color: "#10b981", beamThickness: 2.5, glowIntensity: 1.1, amplitude: 0.85, showCenterLine: true } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "spotify-pill", showBpmKey: false, showTimer: true, showAudioSpecs: false, accentColor: "#10b981", titleFont: "jakarta", badgeStyle: "glass" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.58, grainIntensity: 0.065 } },
    ],
  },

  // --- 5. SYNTHWAVE CYBER OUTRUN ---
  // Aesthetic: retro 80s sci-fi. Cyber grid, cassette hero, circular donut
  // spectrograph, CRT oscilloscope beam, cyberpunk HUD telemetry.
  {
    id: "synthwave-outrun",
    name: "Synthwave Cyber Outrun",
    description: "Retro 80s sci-fi grid, circular spectrograph, cassette deck hero, neon CRT oscilloscope, and cyberpunk telemetry HUD.",
    aspectRatio: "16:9",
    effects: [
      { id: "bg-cyber-grid",
        enabled: true,
        options: { gridColor: "#a855f7", gridSpacing: 88, starCount: 55, reactToKick: true } },
      { id: "vis-circular-donut",
        enabled: true,
        options: { barCount: 72, maxBarLength: 70, barWidth: 4, rotationSpeed: -0.18, color: "#ec4899", glow: true, kickReaction: true } },
      { id: "hero-cassette-deck",
        enabled: true,
        options: { shellColor: "#09090b", accentColor: "#a855f7", tapeSpeed: 1.1 } },
      { id: "vis-neon-oscilloscope",
        enabled: true,
        options: { color: "#22d3ee", beamThickness: 2.8, glowIntensity: 1.4, amplitude: 1.0, showCenterLine: false } },
      { id: "part-bokeh-back",
        enabled: true,
        options: { layer: "back", particleCount: 35, baseSpeed: 0.55, emberColor: "#a855f7", reactToKick: true } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "tech-hud", showBpmKey: true, showTimer: true, showAudioSpecs: true, accentColor: "#a855f7", titleFont: "mono", badgeStyle: "outline" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.65, grainIntensity: 0.03 } },
    ],
  },

  // --- 6. AMBIENT FLUID MESH ---
  // Aesthetic: vibrant flowing organic shapes. Mesh gradient, thumping art,
  // fluid wave ribbon, floating bokeh, minimalist single-line dock HUD.
  {
    id: "ambient-fluid-mesh",
    name: "Ambient Fluid Mesh",
    description: "Flowing multi-point mesh gradient with thumping artwork, fluid neon wave ribbon, floating particles, and a minimalist dock HUD.",
    aspectRatio: "16:9",
    effects: [
      { id: "bg-mesh-gradient",
        enabled: true,
        options: { speed: 0.9, darken: 0.28, reactToKick: true, customAccent: "#6366f1" } },
      { id: "hero-thumping-art",
        enabled: true,
        options: { thumpStrength: 0.10, glowIntensity: 0.9, glowColor: "#6366f1", cornerRadius: 28, sizeScale: 1.0 } },
      { id: "vis-fluid-wave",
        enabled: true,
        options: { wavePoints: 72, waveHeight: 70, strokeColor: "#818cf8", mirror: true, glow: true } },
      { id: "part-bokeh-back",
        enabled: true,
        options: { layer: "back", particleCount: 45, baseSpeed: 0.4, emberColor: "#a5b4fc", reactToKick: false } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "minimal-dock", showBpmKey: true, showTimer: false, showAudioSpecs: false, accentColor: "#818cf8", titleFont: "jakarta", badgeStyle: "glass" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.50, grainIntensity: 0.025 } },
    ],
  },

  // --- 7. CINEMATIC BILLBOARD ---
  // Aesthetic: premium poster / editorial. Blurred cover, cover art card with
  // drop shadow, circular donut, adaptive tri-band EQ, centered poster HUD.
  {
    id: "billboard-cinematic",
    name: "Cinematic Billboard Poster",
    description: "Premium editorial poster — cover art card with deep shadow, circular donut spectrograph, tri-band EQ visualizer, and centered billboard HUD.",
    aspectRatio: "16:9",
    effects: [
      { id: "bg-blurred-cover",
        enabled: true,
        options: { blurAmount: 60, darken: 0.68, zoom: 1.3, pulseWithBass: false } },
      { id: "vis-circular-donut",
        enabled: true,
        options: { barCount: 88, maxBarLength: 65, barWidth: 3, rotationSpeed: 0.08, color: "#f8fafc", glow: true, kickReaction: true } },
      { id: "hero-cover-art-shadow",
        enabled: true,
        options: { cornerRadius: 28, shadowDepth: 55, shadowOpacity: 0.9, cardScale: 0.88, borderWidth: 1.5, reactToKick: true } },
      { id: "vis-adaptive-triband",
        enabled: true,
        options: { mode: "triband-eq", showLabels: true, showPercentages: false, dockHeight: 80, lowColor: "#f59e0b", midColor: "#10b981", highColor: "#06b6d4" } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "billboard", showBpmKey: true, showTimer: true, showAudioSpecs: false, accentColor: "#fbbf24", titleFont: "outfit", badgeStyle: "glass" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.68, grainIntensity: 0.04 } },
    ],
  },

  // =========================================================================
  // PORTRAIT PRESETS (9:16) — YouTube Shorts / TikTok / Reels
  // =========================================================================

  // --- 8. BASS THUMP ENERGY (Shorts) ---
  // Aesthetic: explosive vertical energy. Thumping artwork bounce on blurred
  // cover, circular donut around art, fire embers, foreground sparks, bold HUD.
  {
    id: "bass-thump-shorts",
    name: "Bass Thump & Energy",
    description: "Explosive vertical energy — speaker bounce, circular donut ring, fire embers, spark burst, and bold Shorts-ready HUD.",
    aspectRatio: "9:16",
    effects: [
      { id: "bg-blurred-cover",
        enabled: true,
        options: { blurAmount: 42, darken: 0.55, zoom: 1.25, pulseWithBass: true } },
      { id: "part-bokeh-back",
        enabled: true,
        options: { layer: "back", particleCount: 55, baseSpeed: 0.55, emberColor: "#fbbf24", reactToKick: false } },
      { id: "vis-circular-donut",
        enabled: true,
        options: { barCount: 64, maxBarLength: 90, barWidth: 5, rotationSpeed: 0.2, color: "#f59e0b", glow: true, kickReaction: true } },
      { id: "hero-thumping-art",
        enabled: true,
        options: { thumpStrength: 0.15, glowIntensity: 1.1, glowColor: "#f59e0b", cornerRadius: 24, sizeScale: 1.0 } },
      { id: "part-fire-embers",
        enabled: true,
        options: { layer: "front", particleCount: 60, baseSpeed: 1.3, reactToKick: true } },
      { id: "part-sparks-fore",
        enabled: true,
        options: { layer: "front", particleCount: 80, baseSpeed: 1.0, emberColor: "#fde68a", reactToKick: true } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "lower-third", showBpmKey: true, showTimer: false, showAudioSpecs: false, accentColor: "#f59e0b", titleFont: "outfit", badgeStyle: "solid" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.68, grainIntensity: 0.04 } },
    ],
  },

  // --- 9. LOFI TAPE CHILL (Shorts) ---
  // Aesthetic: vertical vintage tape player. Blurred cover, cassette deck,
  // warm dust bokeh, fluid wave ribbon dock, Spotify pill.
  {
    id: "lofi-tape-shorts",
    name: "Lofi Tape Chill Shorts",
    description: "Vertical vintage cassette player — warm dust bokeh, fluid wave dock, and Spotify glass pill widget.",
    aspectRatio: "9:16",
    effects: [
      { id: "bg-blurred-cover",
        enabled: true,
        options: { blurAmount: 46, darken: 0.56, zoom: 1.2, pulseWithBass: false } },
      { id: "part-bokeh-back",
        enabled: true,
        options: { layer: "back", particleCount: 48, baseSpeed: 0.32, emberColor: "#fcd34d", reactToKick: false } },
      { id: "hero-cassette-deck",
        enabled: true,
        options: { shellColor: "#292524", accentColor: "#fbbf24", tapeSpeed: 0.82 } },
      { id: "vis-fluid-wave",
        enabled: true,
        options: { wavePoints: 56, waveHeight: 60, strokeColor: "#fbbf24", mirror: true, glow: true } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "spotify-pill", showBpmKey: false, showTimer: true, showAudioSpecs: false, accentColor: "#fbbf24", titleFont: "jakarta", badgeStyle: "glass" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.62, grainIntensity: 0.06 } },
    ],
  },

  // --- 10. DRILL TRAP SHORTS ---
  // Aesthetic: hard-hitting vertical drill / UK rap energy.
  // Thumping art, simple bars, fire embers, RGB glitch, billboard HUD.
  {
    id: "drill-trap-shorts",
    name: "Drill Trap Shorts",
    description: "Vertical 808 drill energy — massive artwork bounce, aggressive simple bars, fire embers, RGB glitch impact, and bold billboard HUD.",
    aspectRatio: "9:16",
    effects: [
      { id: "bg-blurred-cover",
        enabled: true,
        options: { blurAmount: 48, darken: 0.72, zoom: 1.3, pulseWithBass: true } },
      { id: "hero-thumping-art",
        enabled: true,
        options: { thumpStrength: 0.18, glowIntensity: 1.3, glowColor: "#dc2626", cornerRadius: 18, sizeScale: 1.0 } },
      { id: "vis-simple-bars",
        enabled: true,
        options: { barCount: 44, maxHeight: 100, barWidth: 7, barGap: 5, roundedCaps: false, mirror: false, gradientTips: false, glow: false, color: "#ef4444", yOffset: 0 } },
      { id: "vis-circular-donut",
        enabled: true,
        options: { barCount: 56, maxBarLength: 80, barWidth: 5, rotationSpeed: -0.25, color: "#dc2626", glow: true, kickReaction: true } },
      { id: "part-fire-embers",
        enabled: true,
        options: { layer: "front", particleCount: 75, baseSpeed: 1.6, reactToKick: true } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "billboard", showBpmKey: true, showTimer: false, showAudioSpecs: false, accentColor: "#ef4444", titleFont: "outfit", badgeStyle: "solid" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.78, grainIntensity: 0.05 } },
      { id: "post-rgb-glitch",
        enabled: true,
        options: { glitchIntensity: 1.3, chromaticShift: 14, onlyOnKick: true } },
    ],
  },

  // --- 11. SYNTHWAVE NEON SHORTS ---
  // Aesthetic: vertical retro-futurism. Cyber grid, solo spinning vinyl,
  // circular donut ring, neon oscilloscope, cyberpunk tech HUD.
  {
    id: "synthwave-neon-shorts",
    name: "Synthwave Neon Shorts",
    description: "Vertical retro-futurism — cyber grid, solo spinning vinyl, circular neon donut, phosphor oscilloscope, and cyberpunk tech HUD.",
    aspectRatio: "9:16",
    effects: [
      { id: "bg-cyber-grid",
        enabled: true,
        options: { gridColor: "#7c3aed", gridSpacing: 72, starCount: 70, reactToKick: true } },
      { id: "vis-circular-donut",
        enabled: true,
        options: { barCount: 60, maxBarLength: 100, barWidth: 5, rotationSpeed: 0.22, color: "#a855f7", glow: true, kickReaction: true } },
      { id: "hero-solo-vinyl",
        enabled: true,
        options: { rpmSpeed: 45, sizeMultiplier: 1.0, reactToKick: true, reflectionSheen: true, centerCoverScale: 0.36 } },
      { id: "vis-neon-oscilloscope",
        enabled: true,
        options: { color: "#e879f9", beamThickness: 2.5, glowIntensity: 1.5, amplitude: 0.9, showCenterLine: false } },
      { id: "part-bokeh-back",
        enabled: true,
        options: { layer: "back", particleCount: 40, baseSpeed: 0.5, emberColor: "#a78bfa", reactToKick: true } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "tech-hud", showBpmKey: true, showTimer: true, showAudioSpecs: false, accentColor: "#a855f7", titleFont: "mono", badgeStyle: "outline" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.65, grainIntensity: 0.028 } },
    ],
  },

  // --- 12. AMBIENT MESH SHORTS ---
  // Aesthetic: dreamy vibrant vertical. Mesh gradient, thumping art, fluid wave,
  // adaptive tri-band EQ, minimal dock HUD.
  {
    id: "ambient-mesh-shorts",
    name: "Ambient Fluid Shorts",
    description: "Dreamy vertical mesh gradient — thumping artwork, fluid wave ribbon, calibrated tri-band EQ, and minimal dock HUD.",
    aspectRatio: "9:16",
    effects: [
      { id: "bg-mesh-gradient",
        enabled: true,
        options: { speed: 1.0, darken: 0.30, reactToKick: true, customAccent: "#818cf8" } },
      { id: "hero-thumping-art",
        enabled: true,
        options: { thumpStrength: 0.11, glowIntensity: 0.95, glowColor: "#6366f1", cornerRadius: 32, sizeScale: 1.0 } },
      { id: "vis-fluid-wave",
        enabled: true,
        options: { wavePoints: 60, waveHeight: 65, strokeColor: "#818cf8", mirror: true, glow: true } },
      { id: "vis-adaptive-triband",
        enabled: true,
        options: { mode: "triband-eq", showLabels: true, showPercentages: true, dockHeight: 75, lowColor: "#f59e0b", midColor: "#10b981", highColor: "#818cf8" } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "minimal-dock", showBpmKey: true, showTimer: false, showAudioSpecs: false, accentColor: "#818cf8", titleFont: "jakarta", badgeStyle: "glass" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.50, grainIntensity: 0.022 } },
    ],
  },

  // --- 13. GLASSMORPHIC SPECTRUM (Shorts) ---
  // Aesthetic: clean premium glass dock. Blurred cover at extreme blur,
  // cover art card with shadow, glassmorphic spectrum bars, minimal stamp HUD.
  {
    id: "glass-spectrum-shorts",
    name: "Glassmorphic Spectrum",
    description: "Ultra-clean premium glass — deep blurred cover, floating album card, glassmorphic spectrum dock, and editorial corner stamp.",
    aspectRatio: "9:16",
    effects: [
      { id: "bg-blurred-cover",
        enabled: true,
        options: { blurAmount: 65, darken: 0.62, zoom: 1.35, pulseWithBass: true } },
      { id: "hero-cover-art-shadow",
        enabled: true,
        options: { cornerRadius: 32, shadowDepth: 60, shadowOpacity: 0.92, cardScale: 0.90, borderWidth: 1.5, reactToKick: true } },
      { id: "vis-spectrum-bars",
        enabled: true,
        options: { barCount: 40, maxHeight: 90, showGlassDock: true, showPeaks: true, adaptiveCalibration: true, mirror: false, color: "#fbbf24" } },
      { id: "part-sparks-fore",
        enabled: true,
        options: { layer: "front", particleCount: 65, baseSpeed: 0.85, emberColor: "#fde68a", reactToKick: true } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "corner-stamp", showBpmKey: true, showTimer: false, showAudioSpecs: true, accentColor: "#fbbf24", titleFont: "outfit", badgeStyle: "glass" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.60, grainIntensity: 0.038 } },
    ],
  },

  // --- 14. VINYL STUDIO SHORTS ---
  // Aesthetic: vertical premium vinyl lounge. Spotlight backdrop, solo vinyl,
  // LED VU meter bars, adaptive hybrid ribbon, classic HUD.
  {
    id: "vinyl-studio-shorts",
    name: "Vinyl Studio Shorts",
    description: "Premium vertical vinyl — studio spotlight, pristine solo spinning vinyl, LED VU console meters, adaptive hybrid ribbon, and classic HUD.",
    aspectRatio: "9:16",
    effects: [
      { id: "bg-radial-spotlight",
        enabled: true,
        options: { spotlightColor: "#fbbf24", intensity: 0.85, radiusMultiplier: 0.9, reactToKick: true } },
      { id: "hero-solo-vinyl",
        enabled: true,
        options: { rpmSpeed: 33.33, sizeMultiplier: 0.95, reactToKick: true, reflectionSheen: true, centerCoverScale: 0.38 } },
      { id: "vis-led-vu-meter",
        enabled: true,
        options: { segmentCount: 20, showDbLabels: true, mode: "stereo", glow: true } },
      { id: "vis-adaptive-triband",
        enabled: true,
        options: { mode: "hybrid-ribbon", showLabels: false, showPercentages: false, dockHeight: 70, lowColor: "#f59e0b", midColor: "#fbbf24", highColor: "#fde68a" } },
      { id: "part-bokeh-back",
        enabled: true,
        options: { layer: "back", particleCount: 40, baseSpeed: 0.38, emberColor: "#fde68a", reactToKick: false } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "classic", showBpmKey: true, showTimer: true, showAudioSpecs: false, accentColor: "#fbbf24", titleFont: "outfit", badgeStyle: "glass" } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.65, grainIntensity: 0.04 } },
    ],
  },

  // --- 15. MAX COVER & DUAL SIDE BARS (16:9) ---
  // Aesthetic: Maximum possible centered cover art with dual side visualizer bars,
  // shockwave rings on drums, beat exposure flash, and clean cinematic post.
  {
    id: "max-cover-side-bars",
    name: "Max Art & Dual Side Bars",
    description: "Maximum size centered cover art with dual side audio visualizer bars (20Hz–20kHz), bass shockwave ripples, and beat exposure flash.",
    aspectRatio: "16:9",
    effects: [
      { id: "bg-blurred-cover",
        enabled: true,
        options: { blurAmount: 36, brightness: 0.35, pulseWithBass: true, pulseScale: 1.05 } },
      { id: "vis-shockwave-rings",
        enabled: true,
        options: { trigger: "drums", color: "#fbbf24", maxRadius: 650, speed: 7, lineWidth: 2.5, glow: true, shape: "rounded-square" } },
      { id: "hero-simple-max-cover",
        enabled: true,
        options: { fitMode: "max-square", padding: 36, cornerRadius: 28, shadowDepth: 55, shadowOpacity: 0.85, borderWidth: 1.5, borderColor: "rgba(255, 255, 255, 0.18)", reactToKick: true, kickScale: 1.03, kickGlow: true } },
      { id: "vis-side-bars",
        enabled: true,
        options: { side: "both-sides", direction: "inward", maxHeight: 95, barCount: 42, barWidth: 6, barGap: 4, edgeOffset: 36, color: "#fbbf24", gradientTips: false, roundedCaps: false, glow: false, mirror: false, routing: "full" } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "corner-stamp", showBpmKey: true, showTimer: true, showAudioSpecs: true, accentColor: "#fbbf24", titleFont: "outfit", badgeStyle: "glass" } },
      { id: "post-exposure-pulse",
        enabled: true,
        options: { trigger: "drums", intensity: 0.30, flashColor: "#ffffff", blendMode: "screen", bloomRadius: 35 } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.55, grainIntensity: 0.035 } },
    ],
  },

  // --- 16. MAX COVER & SIDE BARS SHORTS (9:16) ---
  // Aesthetic: Maximum square center cover art for TikTok/Shorts with side bars,
  // shockwave rings, beat exposure flash, and mobile HUD.
  {
    id: "max-cover-side-bars-shorts",
    name: "Max Art & Side Bars Shorts",
    description: "Maximum square centered cover art with side audio bars (20Hz–20kHz), bass shockwave rings, and beat exposure flash formatted for 9:16 Shorts/Reels.",
    aspectRatio: "9:16",
    effects: [
      { id: "bg-blurred-cover",
        enabled: true,
        options: { blurAmount: 42, brightness: 0.32, pulseWithBass: true, pulseScale: 1.06 } },
      { id: "vis-shockwave-rings",
        enabled: true,
        options: { trigger: "drums", color: "#fbbf24", maxRadius: 550, speed: 6.5, lineWidth: 2.5, glow: true, shape: "rounded-square" } },
      { id: "hero-simple-max-cover",
        enabled: true,
        options: { fitMode: "max-square", padding: 36, cornerRadius: 28, shadowDepth: 60, shadowOpacity: 0.88, borderWidth: 1.5, borderColor: "rgba(255, 255, 255, 0.2)", reactToKick: true, kickScale: 1.035, kickGlow: true } },
      { id: "vis-side-bars",
        enabled: true,
        options: { side: "bottom", direction: "inward", maxHeight: 110, barCount: 44, barWidth: 7, barGap: 4, edgeOffset: 120, color: "#fbbf24", gradientTips: false, roundedCaps: false, glow: false, mirror: false, routing: "full" } },
      { id: "hud-track-info",
        enabled: true,
        options: { layoutStyle: "classic", showBpmKey: true, showTimer: true, showAudioSpecs: false, accentColor: "#fbbf24", titleFont: "outfit", badgeStyle: "glass" } },
      { id: "post-exposure-pulse",
        enabled: true,
        options: { trigger: "drums", intensity: 0.32, flashColor: "#ffffff", blendMode: "screen", bloomRadius: 40 } },
      { id: "post-vignette-grain",
        enabled: true,
        options: { vignetteStrength: 0.65, grainIntensity: 0.04 } },
    ],
  },
];
